# Generated by Django 2.2.3 on 2019-09-29 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('blog', '0008_auto_20190926_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sites',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
            preserve_default=False,
        ),
    ]
