# Generated by Django 2.2.3 on 2019-09-29 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_sites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sites',
        ),
    ]
